services:
  ligar:
    build:
     context: .
     dockerfile: ./docker/Dockerfile.txt
    container_name: micro_front
    ports:
      - "3000:3000"
    networks:
      - minha-rede
      
networks:
  minha-rede:
    external: true
